### ISSUE TITLE
Delete groups in openshift 

### ISSUE THREAD

**Issue by simonstumpf** [redhat-cop/group-sync-operator#103] opened 2021-07-14 10:52 UTC
If a group gets deleted in one of the external provides (in my case Azure) currently the group will keep existing in openshift. 

Could it be possible to also check if a group got deleted and then also delete it in openshift?

**Comment by Jmainguy** [comment] 2021-07-22 19:39
anything is possible, code would have to be added which checked the groups it wants to sync, with the groups it currently has, and then delete any groups not in the new list of groups.

**Comment by sabre1041** [comment] 2021-07-23 23:15
Duplicate of #34

**Closed** 2022-03-01 06:36 UTC
